# Project information
site_name: ChatPlus Documentation
site_url: https://crystalflxme.github.io/ChatPlus/
site_author: Crystalflxme
site_description: For your chat modification and formatting needs!

# Repository
repo_name: crystalflxme/chatplus
repo_url: https://github.com/crystalflxme/chatplus
edit_uri: ""

theme:
  name: null
  custom_dir: material
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - tabs
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/crystalflxme
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/crystalflxme

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home:
    - Welcome: index.md
    - Examples: examples.md
  - Setup:
    - Getting started: setup/getting-started.md
    - System gotchas: setup/gotchas.md
    - Editing the config: setup/config.md
    - Dynamic client chat options: setup/dynamic-client-chat-options.md
  - Maintaining:
    - Updating ChatPlus: maintaining/updating.md
  - API:
    - SpeakerPlus: api/speakerplus.md
    - Util: api/util.md